### ISSUE TITLE
[Bug]: Email validation missing for dot (.) in contact form

### ISSUE THREAD

**Issue by 54J4N** [piyushgarg-dev/piyushgargdev-nextjs#1013]
### Describe the bug

Currently, the contact me box on the website has three fields: name, email, and message, along with a submit button. If the user forgets to include the @ symbol in the email section, the system correctly alerts about the missing @. However, if the user forgets the dot (.) before com in the email, there is no alert. 

### To Reproduce

1. Visit the website: www.piyushgarg.dev
2. Navigate to the contact me section.
3. In the email box, enter an email address without the dot (.) before the com.
4. Submit the form 

### Expected behavior

When submitting the contact form, the system should provide an alert if the email address is missing the dot (.) before the com.

### Screenshots/Videos

![dotmissing](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/122589374/458bf5d6-de70-4e10-aaf8-215af049e679)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by hmshuv** [comment]
fixing #1013
