### ISSUE TITLE
How to setup this project ?

### ISSUE THREAD

**Issue by TheMohit2003** [piyushgarg-dev/piyushgargdev-nextjs#104]
**Describe the issue**
I am not able to set up this project on my local machine, I need some guidance concerning how to set up the project on my local machine.

**Expected behavior** 
Can I get a video on how to set up the project as well as proper documentation that is step-by-step commands of what to follow to set up the project?

**Comment by piyushgarg-dev** [comment]
Great Idea, I'll make a video on it ✨
Thanks, @TheMohit2003
