### ISSUE TITLE
[Feautre]: NavBar Element could have Icon corresponding to their title 

### ISSUE THREAD

**Issue by MeganusWesker** [piyushgarg-dev/piyushgargdev-nextjs#106]
**If navbar element will have icons corresponding to their title it will look good to human eyes and is easy to navigate** 

![Screenshot (180)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/85287098/ffcd665a-6d4c-4128-951b-b69e8a7f05f5)

**instead of just having anker tag**

we could have a li tag in li tag  we could have a icon and than  the anker tag with it

**Comment by TheMohit2003** [comment]
What icons do you think should be used, can you share some resources @MeganusWesker ?

**Comment by MeganusWesker** [comment]
@TheMohit2003  
for home we could home icon like this
![25694](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/85287098/92a827b6-1e03-4568-85cc-82f23e9bffa2)

not really like this it just a kind of refenrce now libary we could use matreial ui or any other for icons or we could use svg as well
