### ISSUE TITLE
[Bug]: Poor User Interface Experience on Small Devices

### ISSUE THREAD

**Issue by akash97184** [piyushgarg-dev/piyushgargdev-nextjs#1064]
### Describe the bug

The user interface exhibits inappropriate rendering on small devices, adversely affecting the overall user experience.

### To Reproduce

1. Open the project on a device with a small screen (e.g., a smartphone or tablet).
2. Observe how the UI elements are not appropriately scaled or positioned, making it challenging to interact with the content.

### Expected behavior

The UI should be responsive and adapt seamlessly to smaller screens, ensuring that users on mobile devices have an optimal experience when accessing the project.

### Screenshots/Videos

![bug](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/114927555/a9145be2-86c1-4643-aa1b-657da19763e1)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by akash97184** [comment]
> I have got the solution in the browser but can't seem to find it on jsx file. If i can get a little help then it would go a long way.

I didn't get you, could you plz elaborate what help do you need.

**Comment by nepalivai** [comment]
I have found the solution to the issue but I can't the section id in the JSX or CSS file.
