### ISSUE TITLE
[Bug]: Overlapping Course Description with used Technologies

### ISSUE THREAD

**Issue by webwiserin** [piyushgarg-dev/piyushgargdev-nextjs#1138]
### Describe the bug

In the course section, First course description is overlapping with described technologies.

### To Reproduce

1. Go to 'piyushgarg.dev'
2. Scroll down to Courses

### Expected behavior

Card height should be auto increase if provided stack is wrapping.

### Screenshots/Videos

<img width="960" alt="image" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/108581626/43d4c738-9392-48ec-8042-b4cbf3171cf1">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by babaazz** [comment]
Yes there is problem related to the responsiveness of the course card

**Comment by babaazz** [comment]
The same bug can be seen in all card components on resizing
