### ISSUE TITLE
[Feature]:There should be a hover effect in the social media icons in home screen.

### ISSUE THREAD

**Issue by chauhansahil150** [piyushgarg-dev/piyushgargdev-nextjs#118]
**Describe the bug**
Currently, there is no hover effect on the social media icons in the website's navbar. Adding a hover effect would enhance the visual appeal and provide better user feedback.

**To Reproduce**
1. Open Website
2. Locate the navbar
3. Locate the social media icons in the top right section.
4. Click on any social media icon

**Expected behavior**
When clicking on a social media icon, there should be a hover effect, such as a change in color or an animation, to provide visual feedback and indicate interactivity.

**Screenshots**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/73341783/837592f7-34b7-4e67-b425-386710377efe)

**Comment by MeganusWesker** [comment]
@TheMohit2003 it will be good with the theme of the site color
