### ISSUE TITLE
bug: [My Gears page] top cards hight

### ISSUE THREAD

**Issue by harshbhange0** [piyushgarg-dev/piyushgargdev-nextjs#12]
**Describe the bug**
The height of the top card in my gear is not right compared to the others because the height of the cards images is incorrect." 

**To Reproduce**
1. Go to 'My Gear tab'
2 Analyze the top row of cards

**Expected behavior**
The card height has to be the same as the others in the middle row and the bottom row

**Screenshots**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/120706512/f11b92d1-4f77-4313-8cb2-55bdd8192289)
the bug ^

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/120706512/4adf0449-815d-4e42-b0c1-66ace2796674)

and want to be^

**Comment by Sky-De** [comment]
Hi there
Assign this to me
I will fix it

**Comment by Sandeep-morya** [comment]
Hello, I had already fixed that and created a pull request.

**Comment by luckyklyist** [comment]
> Hello, I had already fixed that and created a pull request.

Make sure to align the pr to the issues .
The issue still don't show any pr related to it .
