### ISSUE TITLE
"[Bug]: Grammatical Error in Testimonial Section on Home Page - Feedback by Student Karan Rana"

### ISSUE THREAD

**Issue by Iamanshuaditya** [piyushgarg-dev/piyushgargdev-nextjs#1262]
### Describe the bug

In the feedback section provided by a student, there is a grammatical error. The sentence currently reads: **"IT IS THE best courses which gives you proper learning regarding react js**."

The correct version should be: " 'IT IS THE best courses' should be corrected to 'IT IS THE best course.' The revised sentence would then read: '**IT IS THE best course which gives you proper learning regarding React JS**.'"

 
![Screenshot 2024-01-19 062917](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/87059568/67e198c4-5068-48f8-abd6-d873381f6ad7)

### To Reproduce

1. Go to 'Testimonial section'
2.Click either on the 'left' or 'right' to browse through the testimonials.
3.Locate the testimonial card associated with 'KARAN RANA.'
![Screenshot 2024-01-19 062917](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/87059568/7ccf71a2-4f8d-4a82-ad5b-1444f5d62559)

### Expected behavior

**"IT IS THE best courses which gives you proper learning regarding react js**  should be **_IT IS THE best course which gives you proper learning regarding React JS_**

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by mcamilletti1** [comment]
I submitted a pull request to fix this! :)

**Comment by officeneerajsaini** [comment]
Hey @Iamanshuaditya 

I noticed the issue you opened, and I'm thinking it might not be a bug but more like user feedback. It seems the reported grammatical issues are specific to a user and might not be code-related.

Just a thought – it might be worth discussing this a bit more before deciding it's a bug. Let me know your thoughts!

**Comment by Iamanshuaditya** [comment]
@officeneerajsaini As i was doing it for first time i don't  i was unaware of this fact . i also don't think this is a bug .

**Comment by officeneerajsaini** [comment]
@Iamanshuaditya  i am also beginner . So i am not like a expert or have a good experience  but i just give my opinions to you .. maybe that is a bug but more like that is typo ... With user feedback so that's users problem .. not ours .. 😂👊🏻 😗
