### ISSUE TITLE
[BUG]: contact section width is not changing on "small-medium" devices.

### ISSUE THREAD

**Issue by Aadarsh-guru** [piyushgarg-dev/piyushgargdev-nextjs#137]
**Describe the bug**
The contact section at the bottom of the home and courses page is not responsive for mobile devices, it is taking a blank space.

**To Reproduce**
1. Go to the home and courses page.
2. Scroll down to the contact section.
4. Inspect the page and see the responsive dimensions of a mobile device.

**Expected behavior**

Contact information and contact form should be vertical for "sm" devices. and the blank space should be utilized.

**Screenshots**
![Screenshot 2023-06-10 085155](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/112774513/ebfbc3d7-335e-4c40-8e8d-848fa70bb788)

**Comment by TheMohit2003** [comment]
@Aadarsh-guru , thanks for your contribution . Are you working on it ?

**Comment by Aadarsh-guru** [comment]
yes

**Comment by luckyklyist** [comment]
pr #138
