### ISSUE TITLE
Feature: Courses Card should be scale up on the hover effect

### ISSUE THREAD

**Issue by Aadarsh-guru** [piyushgarg-dev/piyushgargdev-nextjs#140]
**Is your feature request related to a problem? Please describe.**
it's a feature that looks good on modern websites, there must be a scale-up effect on the hover of the courses card on the courses page.

**Describe the solution you'd like**
while hover effect the course card should get box-shadow and scale up by 0.2%

![Screenshot 2023-06-10 095929](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/112774513/966b9f65-80b2-4e1c-aa5a-5fcfc6ad4cb7)

**Comment by luckyklyist** [comment]
pr #143
