### ISSUE TITLE
[Bug]: Apostrophe entity number instead of apostrophe symbol.

### ISSUE THREAD

**Issue by Singh2655** [piyushgarg-dev/piyushgargdev-nextjs#1410]
### Describe the bug

On the homepage, within the YouTube section, on the video card featuring content related to Devin AI, an issue has been observed where apostrophe entity numbers are displayed instead of the appropriate apostrophe symbol.

### To Reproduce

1. Go to Home page
2. Scroll down to youtube section
3. See error in "AI Ended Jobs" card

### Expected behavior

Apotrophe symbol should be displayed instead of it's entity number

### Screenshots/Videos

![Uploading Screenshot 2024-04-01 204126.png…]()

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by ghost** [comment]
The card which you are talking about that is not displaying in the youtube section.
may be the card is removed from there.

if exist then please provide more details.

**Comment by Singh2655** [comment]
> The card which you are talking about that is not displaying in the youtube section. may be the card is removed from there.
> 
> if exist then please provide more details.

It appears that the card is no longer included in the results obtained by API fetch, which maps through five available cards.
