### ISSUE TITLE
Bug: Unwanted Extra Space showing up in Mobile View HomePage

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/piyushgargdev-nextjs#146]
**Describe the bug**
Extra space is shown up on the homepage when opened on the mobile device.

**To Reproduce**
1. Go to `piyushgarg.dev` on a real mobile device
2. See the extra space on the right side

**Expected behavior**
There should be no extra empty space there.

**Screenshot**
![IMG_5660](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/44976328/dcfd2f94-3bd2-4aef-b85c-1b63324b81aa)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: IOS 16
 - Browser Safari on iPhone

**Comment by TheMohit2003** [comment]
The reason for that extra space is the form . Once the form is made responsive , the problem would be solved : 
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/99909551/535026ab-8326-4300-b11f-078c6624a8e0)

**Comment by piyushgarg-dev** [comment]
@TheMohit2003 Good Catch, Do you think that PR #138 will fix this issue?

**Comment by piyushgarg-dev** [comment]
Dependent Issue #137 🙌🏻

**Comment by piyushgarg-dev** [comment]
Closing this issue in Ref #138
