### ISSUE TITLE
[Bug]: Inappropriate borders on few elements

### ISSUE THREAD

**Issue by cyber-scribe** [piyushgarg-dev/piyushgargdev-nextjs#1531]
### Description

Borders are appearing on some elements which negatively impact the overall look and feel of the user interface.

### To Reproduce

1.Navigate to the Blogs page.
2. Locate the sign-in options.
3. Observe the borders around the logo.

### Expected behavior

These elements should not have borders that detract from the overall design.

### Video

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/143942536/9279c960-3b24-4de1-8774-54a5ff525bac

**Comment by zaidkhuroo** [comment]
Regarding issue: #1531
This issue can't be fixed as the blog option redirects to another website itself, and is linked with this button through an anchor tag. So there is no code for the blog page in this repo. I've linked a video to this comment for the demonstration.
[Screencast from 28-06-24 11:38:02 AM IST.webm](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/108170101/883209c3-34be-446e-aeb0-66ebf125e4e3)
