### ISSUE TITLE
[Bug]: Typo mistake in the word "Piyushh" in the home page of the website

### ISSUE THREAD

**Issue by ankitdas-dev** [piyushgarg-dev/piyushgargdev-nextjs#1548]
### Describe the bug

There is a typo mistake in the word "Piyushh" in the home page

### To Reproduce

1. Go to the home page.
2. Scroll down.
3. See the error.

### Expected behavior

It should  be "Piyush".

### Screenshots/Videos

![Screenshot 2024-07-05 161911](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/151054379/9f471c7e-68fa-4dfc-bfb5-3b92e95c69fb)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by mohitdudhat22** [comment]
In the screenshot, it already says "Piyush." I can't see any typos here.

**Comment by sujal12344** [comment]
There is no typo. And in the screenshot it is "Piyush", not " Piyushh". 🧐

**Comment by sujal12344** [comment]
Please close the issue..

**Comment by adityakukade32** [comment]
There is no typo error. i can see screenshot

**Comment by sujal12344** [comment]
please close this isuue @piyushgarg-dev @ankitdas-dev
