### ISSUE TITLE
[Bug]: [Join Discord  Server] Button Click Not Working on [https://www.piyushgarg.dev/]

### ISSUE THREAD

**Issue by mayurr7** [piyushgarg-dev/piyushgargdev-nextjs#1604]
### Describe the bug

The Join Discord Server  button on the Home page does not function as expected when clicked.

### To Reproduce

1. Go to 'https://www.piyushgarg.dev/.'
2. Click on 'Join Discord  Server Button'
3. See error

### Expected behavior

After clicking the Join  Discord  Server Button  , on the Discord website  Piyush Garg account should be appear.

### Screenshots/Videos

https://github.com/user-attachments/assets/97e1f7f2-f2bb-4f60-853e-fd98a0cdf5fd

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Manish-k723** [comment]
It's Working normally.
