### ISSUE TITLE
[BUG]: There may be a syntax error in line 103 in the Header.jsx file

### ISSUE THREAD

**Issue by pawan-maurya** [piyushgarg-dev/piyushgargdev-nextjs#161]
**Describe the bug**
There may be a syntax error in line 103 in the _Header.jsx_ file
I guess there is an extra closing bracket ( parentheses ) in _line 103_

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'components/Header/Header.jsx '
2. Scroll down to 'line 103'
Or follow click link to go to the [line 103](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/blob/8319260adcbf6175f467218da7a48a43b37a11fb/components/Header/Header.jsx#L103)
4. See the error

**Screenshots**
![syntax error in line 103](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/19765392/dc9c8773-6699-4f96-871e-1a4b3c24ffe1)

**Expected behaviour**
need to remove the extra bracket

**Solution screenshot - that maybe apply**
![syntax error in line 103 - solution](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/19765392/17420c84-0cdd-4b05-9ea9-06667f8ab64b)

**Comment by piyushgarg-dev** [comment]
Great Spot 🙌🏻, Thanks for reporting 🚀
