### ISSUE TITLE
[Bug]:In Students feedback testimonials height of Student Image should be same

### ISSUE THREAD

**Issue by sheryarking5** [piyushgarg-dev/piyushgargdev-nextjs#166]
**Describe the bug**
In Students feedback testimonials height of Student Image is not same which not looks good and cause some UI inconsistency

**To Reproduce**
1. Go to 'Home page''
2. Scroll down to 'Testimonial section'
3. See student's image

**Expected behavior**
In Students feedback testimonials height of Student Image should be same

**Screenshots**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/107617184/b3420447-9485-4b1e-9a1d-b74680b81841)

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/107617184/8cadd004-8569-42ac-920d-aebf1b4c079d)

**Comment by piyushgarg-dev** [comment]
Amazing @sheryarking5 ✨
