### ISSUE TITLE
[bug] Non-functional Login Button in Navbar Section

### ISSUE THREAD

**Issue by HEMANTH123SR** [piyushgarg-dev/piyushgargdev-nextjs#169]
**Description**
The login button in the navbar section of the website is not functioning as expected. When attempting to click on the login button, no action is triggered, and the expected login functionality does not occur.

**Steps to Reproduce**
1. Go to the website homepage.
2. Locate the navbar section at the top of the page.
3. Look for the login button within the navbar.
4. Click on the login button.
5. Observe that no response or action occurs.

**Expected Behavior**
When clicking on the login button in the navbar section, it should initiate the login process, redirecting the user to the login page or triggering a login modal to appear.

**Screenshots**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/116257590/51be1019-7e54-45bc-8f3e-61233e161ffe)

**Desktop**
- OS: [Specify the operating system, e.g., Windows 10]
- Browser: [Specify the browser used, e.g., Google Chrome]
- Version: [Specify the browser version if known]

**Smartphone**
- Device: [Specify the device used, e.g., iPhone X]
- OS: [Specify the operating system, e.g., iOS 14]
- Browser: [Specify the browser used, e.g., Safari]
- Version: [Specify the browser version if known]

**Additional Context**
[Provide any additional information or context that might be helpful in understanding or reproducing the issue.]

**Comment by ChavvaNarayana** [comment]
I would like to work on it, but could you please specify what features you need to add to the button functionality

**Comment by piyushgarg-dev** [comment]
Hey @HEMANTH123SR, Amazing Catch ✨
This issue has been fixed in commit https://github.com/piyushgarg-dev/piyushgargdev-nextjs/commit/c9cadffb85fbd8aa172970b761f144a5499ae0e1
Thanks a lot for contributing ❤️
