### ISSUE TITLE
[Bug]: minor changes in header height and duplicate style in blog.jsx

### ISSUE THREAD

**Issue by harsh11-11** [piyushgarg-dev/piyushgargdev-nextjs#171]
### Describe the bug

there are 2 minor bugs in this repo now:
1. Header height is not same as of div container.
2. there is been use style={{}} two times, which is an error.

### To Reproduce

for problem 1
1. Go to 'components/UI/' 
2. Click on 'Blog.jsx'
3. Scroll down to 'line 31'

for problem 2
1. go to website and inspect then click on header 
2. in styles section scroll down uncheck border width.
3. then you will see the difference.

### Expected behavior

for problem 1:

There will no error message

for problem 2:

Both div containers height and headers height will match.

### Screenshots/Videos

Problem 1:

<img width="1680" alt="Screenshot 2023-06-12 at 12 13 25 PM" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/938e70c3-9638-4ebf-b5c2-183932e6c8c7">

Problem 2:

<img width="1680" alt="Screenshot 2023-06-12 at 12 16 04 PM" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/7f01b997-02a3-4ac3-b1e4-0cfe9b7f32b0">
<img width="1680" alt="Screenshot 2023-06-12 at 12 12 27 PM" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/14d90a52-8da0-42df-89fe-0a78e7841b63">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by hemantwasthere** [comment]
Great @harsh11-11, are you working on this issue?

**Comment by harsh11-11** [comment]
@piyushgarg-dev check this minor change
