### ISSUE TITLE
feat: There should be hover effect on the social media icons in navbar.

### ISSUE THREAD

**Issue by simrin3308** [piyushgarg-dev/piyushgargdev-nextjs#175]
There should be hover effect on the social media icons in navbar. It will increase the user experience. This feature was earlier implemented but now is not working after the latest merges.

I have corrected the fix. Given hover effect on social media icons again.

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110960043/da688c28-a57c-4c59-988e-06efdc9f05a3)

**Comment by ChavvaNarayana** [comment]
Hey, @simrin3308 is the bug fixed now ?
I would like to work on it. 
Cause I have already implemented that feature but now with the latest commits, it is not working.
