### ISSUE TITLE
[Bug]: change colour after hover on navRIght_Icons from #01d293 to --site-theme-color

### ISSUE THREAD

**Issue by harsh11-11** [piyushgarg-dev/piyushgargdev-nextjs#181]
### Describe the bug

Minor change in colour we used a variable define globally rather a colour number. Maintaining consistency in code.

### To Reproduce

1. Go to 'Homepage'
2. Hover on 'Navbar icons'

### Expected behavior

Consistency in code, use previously define var, rather than using new colour.

### Screenshots/Videos

<img width="1680" alt="Screenshot 2023-06-12 at 3 56 38 PM" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/75314730/06b1be4c-b8cd-4871-9a0b-f4ac68111a0c">

### Additional context

@simrin3308 had already did this just upgrading it.

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by piyushgarg-dev** [comment]
Awesome 🙌❤️

**Comment by simrin3308** [comment]
Amazing🔥🔥
