### ISSUE TITLE
[Bug]:  It open another page when we click on the rection button of blog section

### ISSUE THREAD

**Issue by PratikKhaire** [piyushgarg-dev/piyushgargdev-nextjs#183]
### Describe the bug

After clicking on the rection button in the blog section it will  go to the content page 

### To Reproduce

1. Go to https://www.piyushgarg.dev/
2. Scroll down to 'blog'

### Expected behavior

It will continue to login in hash node and add rection 

### Screenshots/Videos

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/109129126/0611566b-d68b-4a8b-8d32-2154314d4131

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by piyushgarg-dev** [comment]
Hey @PratikKhaire 
Amazing Description and Issue ✨

I feel that this is not an issue because you can add reactions on the blog website, this is only displaying the reactions ✨


Thanks a lot for contributing ❤️
