### ISSUE TITLE
Wrong Text of the Button on Home Page

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/piyushgargdev-nextjs#2]
**Describe the bug**
The text of the button says "Join Open Source BootCamp" but instead takes to the discord server invite.

**To Reproduce**
1. Go to the Home Page
2. Locate the Button that says Join Open Source BootCamp
3. Click on the button
4. You'll be redirected to the Discord invite

**Expected behavior**
The button must say "Join Discord Server" or anything related.

**Screenshots**
![Screenshot 2023-06-05 at 9 27 06 PM](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/44976328/812de530-8d1e-432c-8f2e-562740a54d06)

**Comment by Animesh59** [comment]
Thank you for awesome _practical_ explanation
