### ISSUE TITLE
[Bug]: Update  youtube subscriber numbers.

### ISSUE THREAD

**Issue by MAYANK-TRIPATH** [piyushgarg-dev/piyushgargdev-nextjs#227]
### Describe the bug

On Home page its need to update number of youtube. As it is 7.39k subscriber but have 7.45k now.
![pen](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/84989130/b2570d12-29c3-4b8b-97d2-51afff3bf1cb)
 

### To Reproduce

1. Go to 'HomePage'
2. Scroll down 'little bit'
![pen](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/84989130/77a80a0e-0abf-4cd2-bd4a-e5a936c8eee3)

### Expected behavior

It should be 7.45k subscribers but it is 7.39k till now.

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by whoafridi** [comment]
@MAYANK-TRIPATH fixed already . close the issue now
