### ISSUE TITLE
[Bug]: Wrong URL is given for GitHub account on blog page of top 5 libraries for React.js 

### ISSUE THREAD

**Issue by yashru17** [piyushgarg-dev/piyushgargdev-nextjs#234]
### Describe the bug

On the blog page of "top 5 libraries for React.js" at the bottom of the page there are given many social account links, URL given for GitHub account is wrong there . When we click on that URL it is showing page not found. 

### To Reproduce

1. Go to 'Blog section given on the top of the Homepage'
2. Scroll Down to the bottom of the page
3. Click on 'Load more' option
4. Find blog on the topic "Top 5 libraries for React.js" and Click on it
5. Scroll down to find social link section
6. Click on GitHub link
7. See error

### Expected behavior

That URL or link should redirect to the account https://github.com/piyushgarg-dev/ 

### Screenshots/Videos

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/138424332/320ae31c-4626-4d95-b7f9-c91d4f0c570a

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by SaketKaswa20** [comment]
We can't solve this here because those blogs are fetched dynamically via graphql (I asked him).

**Comment by yashru17** [comment]
> We can't solve this here because those blogs are fetched dynamically via graphql (I asked him). 

Ok fine.... should I close the issue?

**Comment by SaketKaswa20** [comment]
Yes, you can.
