### ISSUE TITLE
[Bug]: Can't open Project

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [piyushgarg-dev/piyushgargdev-nextjs#236]
### Describe the bug

I try a lot to set up this project. 
but I don't understand why this is showing!

### To Reproduce

setup project by seeing the guidelines.

### Expected behavior

.

### Screenshots/Videos

<img width="960" alt="image" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/69814563/dd41eb40-466d-434e-939f-50904890e448">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by MrTea7171** [comment]
You to clone the project and try again. This is not happening for me
