### ISSUE TITLE
improve cards design 

### ISSUE THREAD

**Issue by iqbalpreet11** [piyushgarg-dev/piyushgargdev-nextjs#24]
**Is your feature request related to a problem? Please describe.**
the cards we are using in website can be modified according to modern websites, it wont change or show any animation on hover.

**Describe the solution you'd like**
we can use transform property on hover to little zoomOut the card and can also apply transition property to make it more smoother,
eg :  .card:hover { 
                         transform : scale(1.15);
                         transition: transform 0.5s;
                     }
NOTE : This is just an example to give you the idea . how we can approach the feature. Things could be different on the code base.
           Thankyou.

Before
![Screenshot (15)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/92119614/7c951299-4961-4d75-9875-c3d5d29b56b3)

After 
![Screenshot (100)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/92119614/6bdd73a8-7dee-4c08-96eb-a00f18445c72)

                           

**Describe alternatives you've considered**

**Additional context**

**Comment by luckyklyist** [comment]
check the pr #28  . I have added the scale with ease-out transition .
