### ISSUE TITLE
[Bug]: Extra Section After footer Area

### ISSUE THREAD

**Issue by sonusharmawevdev** [piyushgarg-dev/piyushgargdev-nextjs#245]
### Describe the bug
[Bug]: Extra Section After footer Area

### To Reproduce

1. Go to 'https://www.piyushgarg.dev/'
2. Scroll down to 'Footer Section'
3. See error [Bug]: Extra Section After footer Area

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/113982847/77be1df3-a893-4518-adb8-32708062af5a)

### Expected behaviour

Expected This 
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/113982847/ecb5884d-4c01-4eaf-a1b2-33755e321782)

To This
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/113982847/6a633654-87f7-4eab-97a3-ced55a6eb102)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by SaketKaswa20** [comment]
I guess, it's solved because I can't see that bug right now.

**Comment by sonusharmawevdev** [comment]
> I guess, it's solved because I can't see that bug right now.
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/113982847/d8028b7f-bfeb-4acb-b2e2-a1e14314bd5f)
 Please check this screenshot.

**Comment by BANGBANG1999** [comment]
It been solved.
I think you should close the issue.
