### ISSUE TITLE
Youtube Stats Mobile View Alignment is not correct

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/piyushgargdev-nextjs#26]
**Describe the bug**
The Alignment of the video cards on Homepage is not centered in mobile view.

**To Reproduce**
1. Go to piyushgarg.dev on Mobile View
2. Navigate to Youtube Stats Section
4. See the youtube videos card

**Expected behavior**
The cards must be centered or take the full width of the screen.

**Screenshots**
<img width="665" alt="Screenshot 2023-06-06 at 10 42 51 AM" src="https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/44976328/6f001c8a-c23c-471e-aa43-d2f1d898e639">

**Comment by eva-lng** [comment]
I'd like to work on this issue
