### ISSUE TITLE
Adding Youtube courses playlists link on websites 

### ISSUE THREAD

**Issue by PredictiveManish** [piyushgarg-dev/piyushgargdev-nextjs#302]
If it will be playlist of youtube be added on to the website it will also increase your youtube courses reaxh and also help those who will find it out there

![playlist issue](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/77712914/bc87d18b-56ff-421b-b531-57639e398696)

**Comment by manish2022-creator** [comment]
I mean as like the JAVA mastery course or Twitter clone there should be some other youtube playlists like open source bootcamp, GraphOL and others.
