### ISSUE TITLE
[FEAT] : Give a cursor : pointer effect on Slider

### ISSUE THREAD

**Issue by nikhillokare** [piyushgarg-dev/piyushgargdev-nextjs#34]
**Is your feature request related to a problem? Please describe.**
Slider don't have a cursor pointer effect

image:

![2023-06-06 (2)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110295778/af505d63-0aa2-4aa8-b81f-c387f624646c)

**Comment by Ahmad-Munab** [comment]
@piyushgarg-dev I sure fixed the issue and submitted a PR, can u merge it? 
first open source contribution btw, Love your videos : )
