### ISSUE TITLE
Update the readme file on the database and OAuth Setup

### ISSUE THREAD

**Issue by hempun10** [piyushgarg-dev/piyushgargdev-nextjs#355]
**Is your feature request related to a problem? Please describe.**
As a beginner developer is it hard to set up the codebase locally and when they don't get the proper instruction they will be frustrated. 

**Describe the solution you'd like**
So, I want to add some database setup and OAuth setup which helps the beginner to understand what to do next, then getting errors which leads to frustration.

**Comment by TanmayDhobale** [comment]
Setting Up Local Codebase with Database and OAuth

Hello! If you're new to the codebase, follow these steps to get started without the frustration:

1. Clone Repo: Fork and clone the repository to your machine:

   git clone https://github.com/your-username/your-forked-repo.git
  
3. Install Dependencies: Navigate to the project directory and install dependencies:
   cd your-forked-repo
   npm install
  

4. Database Setup: 

   - Set up a local database (like MySQL or PostgreSQL).
   - Copy `.env.example` to `.env` and update with your database details:

     DB_HOST=localhost
     DB_PORT=your-database-port
     DB_USER=your-database-username
     DB_PASS=your-database-password
     DB_NAME=your-database-name


5. OAuth Configuration: 

   - Create an OAuth app in the developer portal.
   - Get the client ID and secret.
   - Update `.env`:

     
     OAUTH_CLIENT_ID=your-client-id
     OAUTH_CLIENT_SECRET=your-client-secret
     OAUTH_CALLBACK_URL=http://localhost:3000/auth/callback
    

6. Start App: Run the app locally and open `http://localhost:3000` in your browser:
npm start

7. Troubleshooting: If you face errors:

   - Check database and OAuth details in `.env`.
   - Ensure dependencies were installed (`npm install`).
   - Confirm the database server is running.

That's it! These steps should help you set up the codebase and configurations. Feel free to seek help if you run into any problems.
