### ISSUE TITLE
[Feat]: Password visible and Not visible option is missing in password input field

### ISSUE THREAD

**Issue by Abhishek9503** [piyushgarg-dev/piyushgargdev-nextjs#378]
**Is your feature request related to a problem? Please describe.**
Password visible and  password not visible icon  is not present in password input field while signing or  registering on  the website  

Expected :
There should be a icon button which toggle the type to input field from password to text so that while registering we can check our expected  password input 

To Reproduce:
1.Scroll down to courses section
2. Click on any course 
3. Now click on buy now
4. Then you will see sign in form 
5. Check the password input field 

Screenshot:

![Screenshot (1169)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/103676667/a7170776-5d2c-4345-8395-8e21b7234f92)

**Comment by 1-Shyam-Agarwal** [comment]
The bug you've uncovered is indeed impressive, but unfortunately, it doesn't seem to exist on my system.

**Comment by Abhishek9503** [comment]
I have closed the issue because the issue was in the third party app not in the main codebase
