### ISSUE TITLE
Feature : Make Email Contact Clickable for Easy Email Redirection

### ISSUE THREAD

**Issue by TheMohit2003** [piyushgarg-dev/piyushgargdev-nextjs#49]
## Is your feature request related to a problem? Please describe.

Yes, the problem is that currently, the user can see the email address in the contact section, but to send an email to Piyush, they have to manually copy the email address and paste it into their email client's "compose" section. This process can be inconvenient and prone to errors.

## Describe the solution you'd like

I would like to have an email icon or a clickable email address in the contact section. When the user clicks on the email icon or the email address, it should automatically redirect them to their default email client, with the "To" field pre-filled with the email address "piyushgarg.dev@gmail.com". This will allow users to send an email to Piyush directly without the need for manual copy-pasting.

## Describe alternatives you've considered

I have considered other alternatives such as providing a contact form on the website, where users can fill in their details and write a message to Piyush. However, implementing the email redirect feature described above would provide a more streamlined and familiar experience for users who are accustomed to using their preferred email client.

## Additional context

Currently, the contact section displays the email address "piyushgarg.dev@gmail.com" without any direct link or functionality. Adding the email redirect feature would enhance user convenience and make it easier for visitors to reach out to Piyush via email.

**Comment by piyushgarg-dev** [comment]
Great Issue Description ✨
