### ISSUE TITLE
[Bug]: Inside Contact.jsx ,"Your Message" textarea should not be resizable beyond specific minimum height.

### ISSUE THREAD

**Issue by JiteshKhurana** [piyushgarg-dev/piyushgargdev-nextjs#518]
### Describe the bug

"Your Message" placeholder is not completely visible when we resize the textarea. It should have a minimum height so that textarea is not resizable beyond a specified limit.

### To Reproduce

1. Go to 'https://piyushgarg.dev/'
2. Scroll down to 'Contact me'
3. Click the "Your Message" field.
4. Resize the "Your Message" textarea to minimum height.

### Expected behavior

It should have a minimum height so that textarea is not resizable beyond a specified limit so that Your Message placeholder is completely visible.

### Screenshots/Videos

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/95995545/4274f340-6e79-47fc-8e65-4e769be580fd

### Please checkmark the following checklist

- [ ] I make sure that similar issue is not opened

**Comment by Godseye-html** [comment]
#497  bug
