### ISSUE TITLE
BUG :  Social media links to be opened at other tabs

### ISSUE THREAD

**Issue by TheMohit2003** [piyushgarg-dev/piyushgargdev-nextjs#58]
**Describe the bug**
The social media icons in the contact me section, when clicked, open the link in the same tab. Thereby taking our user away from the portfolio website.

**To Reproduce**
1. Go to 'Home Page'
2. Scroll down to 'Contact me'
3. Now click on the icons

**Expected behavior**
When the user clicks any of those social media links , it should open in a separate tab.

**Screenshots**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/99909551/97492c4b-4fc8-45e0-b9a0-33b093f1af7a)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Additional context**
The social media icons which are present on the navbar , if clicked take the user to separate tab but same is not the case with the icons in the contact me section .

[**Video**](https://www.awesomescreenshot.com/video/18098160?key=1ddb0122a8b31400492b3f3fde4d3053)

**Comment by SahilRw** [comment]
@piyushgarg-dev I would like to work on this issue. Would you please assign this issue to me?
