### ISSUE TITLE
[Bug]: Getting Server Error while navigating to login page

### ISSUE THREAD

**Issue by unnatijadhav** [piyushgarg-dev/piyushgargdev-nextjs#590]
### Describe the bug

When I click on Login, I get below error in my local machine.

![Capture](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/53641854/f849900b-7d1a-4a20-9186-a3eeca9c3af1)

I think the env.local file should be updated with the properties mentioned 
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/53641854/7adf0fad-ab3d-45b3-91c5-b88c4628c2f1)

Can you please mentioned what should be those values or how to populate them as readme document does not say anything about it.

### To Reproduce

1. Go to 'http://localhost:3000'
2. Click on 'Login'
3. See error

### Expected behavior

Login page should appear with no error

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Bhargav0108** [comment]
I guess this would help in resolving your issue - 
[https://stackoverflow.com/questions/55604057/what-is-mongo-url-and-what-should-it-be-set-to](url)

**Comment by Bhargav0108** [comment]
I guess this can help you resolve your issue - 
[](https://stackoverflow.com/questions/55604057/what-is-mongo-url-and-what-should-it-be-set-to)

**Comment by Bhargav0108** [comment]
I guess this can help you resolve your issue - https://stackoverflow.com/questions/55604057/what-is-mongo-url-and-what-should-it-be-set-to

**Comment by unnatijadhav** [comment]
Thanks @Bhargav0108
