### ISSUE TITLE
Youtube Channel Stats are not up-to-date.

### ISSUE THREAD

**Issue by prathamesh2525** [piyushgarg-dev/piyushgargdev-nextjs#6]
**Describe the bug**
Youtube Channel Stats are not up to date.

**To Reproduce**
1. Go to [piyushgarg.dev](https://www.piyushgarg.dev/)
2. Scroll down to 'Youtube Section'
4. See error : Displayed Stats → 1.01K subscribers | 114 videos 

**Expected behavior**
Current Channel Stats on (Jun 5 2023): 5.12K subscribers | 214 videos 

**Screenshots**
![Screenshot from 2023-06-05 22-13-12](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/61145586/4f2ee416-4f7a-4c56-a7b0-1b0ad9d08aa6)

**Comment by piyushgarg-dev** [comment]
Good Catch ✨
