### ISSUE TITLE
[Feat]: Buttons should lead to the desired link

### ISSUE THREAD

**Issue by ashleychandy** [piyushgarg-dev/piyushgargdev-nextjs#601]
Problem:
Hovering on the buttons feels like it is correlated with a link

Solution:

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/76095880/6f07908d-953d-46df-9f04-2a320cabd427)

Clicking on this button should lead to the featured page:  https://www.youtube.com/@piyushgargdev/featured

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/76095880/b70e8129-f0ca-4c8a-b1cd-56e270949218)

Clicking on this button should lead to the videos page: https://www.youtube.com/@piyushgargdev/videos

To Reproduce:

1:  Go to https://www.piyushgarg.dev/
2: Navigate to the Home Page.
3: Scroll to the " Youtube " section

**Comment by github-harshit** [comment]
I would like to work on this
