### ISSUE TITLE
BUG : github icon not present in Navbar social media section

### ISSUE THREAD

**Issue by TheMohit2003** [piyushgarg-dev/piyushgargdev-nextjs#62]
**Describe the bug**
The Github icon is present in the contact me section but not in Navabar

**To Reproduce**
1. Just compare the navbar social media icons and the one in the contact me section

**Expected behavior**
There should be a GitHub icon in the navbar

**Screenshots**

Navbar :  
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/99909551/305ca97e-acc0-42b1-8867-3b996f00ae71)
  

Contact me :  
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/99909551/05160374-c765-480a-8265-cae287cc2db7)
  

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Chrome]

**Comment by nikhillokare** [comment]
fix #62 Now check the GitHub icon present in navbar social

Before :
![2023-06-07](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110295778/540c764e-8b36-43dd-a052-34d2a1bc4154)

After :

![2023-06-07 (2)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110295778/0d4db530-651a-4df9-85f8-e365b6e06063)
