### ISSUE TITLE
Email Client should be launched as email icon is clicked.

### ISSUE THREAD

**Issue by mohdsaquibusmani** [piyushgarg-dev/piyushgargdev-nextjs#65]
**Is your feature request related to a problem? Please describe.**
Email Client should be launched as email icon is clicked.

**Additional context**

![Screenshot (388)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/122152694/a5b38d99-404c-4285-8a18-ebcff3ae5771)

**Comment by piyushgarg-dev** [comment]
Closing in ref to #51
Thanks a lot for contributing 🚀
