### ISSUE TITLE
[BUG] In -Contact me section social media icon open in existing tab fix this and open a icon in new tab.  

### ISSUE THREAD

**Issue by nikhillokare** [piyushgarg-dev/piyushgargdev-nextjs#67]
**Describe the bug**
 In contact me section social media icon open in existing tab fix this and open a icon in new tab 

**To Reproduce**
1. Go to -  UI
2. Click on  - Contact.jsx
3. Classname - classes.social__links

**Screenshots**

![2023-06-07 (3)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110295778/bcb8a8ad-b6d1-4add-8024-90a1576a42bc)

**Comment by nikhillokare** [comment]
thank you recall @TheMohit2003

**Comment by TheMohit2003** [comment]
@nikhillokare, you can close this issue if you want.
