### ISSUE TITLE
feature to add typing effect in home page in name

### ISSUE THREAD

**Issue by ankush-r** [piyushgarg-dev/piyushgargdev-nextjs#698]
**Description :**
the text in home page "I'm Piyush Garg" is constant without any behavior. 
Add an intriguing effect like someone is typing.

**Reproduce:**
1.fork the repo
2.run the main file.
3.check the homepage.

**Expected :**
add a typing effect.

**Screenshot:**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/97425647/f3628aff-b7ee-49fb-a801-a743f3aae238)

**Comment by sahith29s** [comment]
Can I be assigned for this issue?

**Comment by sahith29s** [comment]
I have asked to assign and added a pull request just after it .
