### ISSUE TITLE
[Bug] sepling extra add "h" i "Piyushh"

### ISSUE THREAD

**Issue by Sonupandit9693** [piyushgarg-dev/piyushgargdev-nextjs#81]
**Describe the bug**
Extra "h" add in "Piyushh"

![Untitled-34](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/111635226/c3cbe13b-ec3d-4e55-a212-7709966f0dab)

**Comment by piyushgarg-dev** [comment]
Fixed by #83
