### ISSUE TITLE
 Typing Error in hero component :  "Incorrect Name"

### ISSUE THREAD

**Issue by lucky1551** [piyushgarg-dev/piyushgargdev-nextjs#82]
**Describe the bug**
A Extra "h" in name: "Piyushh". On the home page. 

**To Reproduce**
1. Go to '.home'
2. Change "Piyushh" to "Piyush"

**Expected behavior**
It should Show "Piyush"

**Screenshots**
Attached

![Screenshot 2023-06-07 at 9 45 51 PM](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/82453126/3dbf88eb-e63c-4b2b-b15b-d3cb32c003f4)

**Comment by piyushgarg-dev** [comment]
Fixed by #83
