### ISSUE TITLE
feature : when you hover on cources it should pop up

### ISSUE THREAD

**Issue by Bhavya-55** [piyushgarg-dev/piyushgargdev-nextjs#86]
**Is your feature request related to a problem? Please describe.**
whenver we are hovering on cource we are unable to understand on which cource our mouse is 

**Describe the solution you'd like**
we should enchance the hover effect on cources as whenver someone hovers the cource should pop up like in youtube videos

**Describe alternatives you've considered**
an alternative could be to give box shadow to cource on hovering

**Additional context**
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/121238674/1a1db520-e25b-44ee-8ea4-76f3aa331b60)

**Comment by TheMohit2003** [comment]
This issue has already been addressed #24 and its pull request is merged as well. 
In case you are not able to see the new features that have been added , kindy go to your main branch and type the below command in you terminal :  
`git pull origin main`

**Comment by piyushgarg-dev** [comment]
Closing this issue in ref #28
@Bhavya-55 Thanks a lot for contribution ✨

CC @TheMohit2003 Thanks Mohit for assist!
