### ISSUE TITLE
[FEAT] hover color on header social media icon

### ISSUE THREAD

**Issue by ritiksharmarj** [piyushgarg-dev/piyushgargdev-nextjs#87]
**Is your feature request related to a problem? Please describe.**
Not a problem. There should be a hover color on header social media icons like the footer so that users can see which icon they're hovering.

**Describe the solution you'd like**
It should be like the footer social media icon.
Hover color - #0a58ca

![piyushdev-hover-color](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/54701022/a55b3885-68bc-4bb1-8fa6-d9394298488e)

**Comment by sidhhantPr** [comment]
can you this assign to me??  it's a very simple solution in a CSS file.

**Comment by TheMohit2003** [comment]
@sidhhantPr, don't wait for the issue to be assigned to you. Just make a PR to this issue if you know the code solution.
