### ISSUE TITLE
[FEAT] social media icons should be either unfilled or filled state

### ISSUE THREAD

**Issue by ritiksharmarj** [piyushgarg-dev/piyushgargdev-nextjs#88]
**Is your feature request related to a problem? Please describe.**
Header and Footer social media icons should be the same either regular/unfilled or bold/filled states to maintain consistency in the design.

**Describe the solution you'd like**
Icons should be **bold/filled** like the header's YouTube or Twitter icon because the page background color is similar to night mode. Bold/filled would be attractive for users.

Header -
![piyushdev-bold-icons](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/54701022/d68bff3b-99ef-4638-a55e-dba8f1e2b187)

Footer -
![piyushdev-bold-icons-footer](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/54701022/9f30437e-a343-45bf-9cf7-acced8f23084)

**Describe alternatives you've considered**
You can either go with **regular/unfilled** state for icons.

**Comment by Drizer909** [comment]
U mean all icons should be appear in either regular form or unfilled .?

**Comment by ritiksharmarj** [comment]
@Drizer909 I mean all header and footer icons should be either regular as https://prnt.sc/USkYOMVeWRDA or filled as https://prnt.sc/MAsEHQ0sFA3K
