### ISSUE TITLE
[BUG]:Testimonial left Button Not Visible on Mobile

### ISSUE THREAD

**Issue by ARPIT871** [piyushgarg-dev/piyushgargdev-nextjs#91]
**Describe the bug**
Currently, on mobile devices, the left button in the testimonial section is not visible, causing a usability issue. This issue impacts the user experience and prevents users from accessing the full functionality of the testimonial section.

**To Reproduce**
1. Open the website on a mobile device.
2. Navigate to the testimonial section.
3. Observe that only the right button is visible, and the left button is missing.

**Expected behavior**
Both the left and right buttons should be visible in the testimonial section on mobile devices, ensuring consistent functionality and design across different screen sizes.

**Screenshots**

![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/87810588/f7542e12-b797-46f5-866c-a8f45086e6e0)

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/87810588/8b504eeb-625e-47b3-ab13-ac517aec6f84

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome

**Additional context**

**Comment by luckyklyist** [comment]
pr #142

**Comment by piyushgarg-dev** [comment]
Amazing Description @ARPIT871 ❤️
Thanks for contributing ❤️

**Comment by ARPIT871** [comment]
> Amazing Description @ARPIT871 ❤️ Thanks for contributing ❤️

Thank you ,can you see my pull request  #148 I did a mistake in that PR
