### ISSUE TITLE
issue: Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".

### ISSUE THREAD

**Issue by Wmg20** [piyushgarg-dev/piyushgargdev-nextjs#95]
**Describe the bug**
Getting this error after yarn dev on localhost:3000:-
Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".

**To Reproduce**
1. Go to ' localhost after running yarn dev '

**Expected behavior**
we should not get this error 

**Screenshots**
![Screenshot (165)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/96992664/982f8b15-187e-42d2-afcb-9af8e0f85bb8)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Comment by TheMohit2003** [comment]
@Wmg20, did you get this error right after setting up the codes or did you change the codes? Can you please define, at what route you countered this error? Because currently at the main branch the local host is running fine and there is no error .
