### ISSUE TITLE
[BUG]: Icons in boxes coming out from the box in the COURSES section

### ISSUE THREAD

**Issue by Falaknaaz123** [piyushgarg-dev/piyushgargdev-nextjs#96]
**Describe the bug**
In the section of Courses of home page, in each box of course icons are coming out from the box ,need to fix and make it more responsive

**To Reproduce**
1. Go to 'inspect'
2. Click on 'Toggle device toolbar'
3. Adjust the sizes in dimension: Responsive bar
4. See the bug in courses section as shown below in the video

**Expected behavior**
all the icons should be in the box division only.

**Screenshots**

https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110015049/73352a80-0dfd-4656-ac45-bedf56b606cb

**Comment by TheMohit2003** [comment]
This issue has already been addressed at issue  #56

**Comment by piyushgarg-dev** [comment]
Amazing Description ✨

**Comment by piyushgarg-dev** [comment]
Closing this issue in ref to #56
