### ISSUE TITLE
Sign-In and login error

### ISSUE THREAD

**Issue by anushkaspatil** [piyushgarg-dev/piyushgargdev-nextjs#966]
### Describe the bug

1. When clicking on login at the navbar, a new window appears showing an error as follows:
    Server Error
    Error: Invalid/Missing environment variable: "MONGODB_URI"
    This error happened while generating the page. Any console logs will be displayed in the terminal window.
2. The same error occurs when sign-in is typed in the terminal, it gets directed to the login page which contains the error.

### To Reproduce

1. Go to login page, the error will be displayed.
Or
1. Click on Home 
2. Scroll down to the Terminal.
3. Type help, followed by whoami, followed by sign-in.
4. See the error.

### Expected behavior

The sign-in page should appear and the user should be able to add their details and should be able to see their name after typing whoami in the terminal.

### Screenshots/Videos

`   lib\mongodbAdapter.js (4:8) @ eval
if (!process.env.MONGODB_URI) {
> throw new Error('Invalid/Missing environment variable: "MONGODB_URI"');
   ^
}
const uri = process.env.MONGODB_URI;`

![Screenshot (149)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/103093836/0a910c5b-5989-4485-b808-5b35f6d1c9b7)
![Screenshot (150)](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/103093836/89ee0b4b-bdca-4c27-a48a-b2588352635c)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by AdityaCubicles45** [comment]
There is no error on the Main Repo as it working fine and the issue you are targetting is on the local server.

**Comment by anushkaspatil** [comment]
Okay, will check it out.
