### ISSUE TITLE
[Bug]: Text of "Full Stack" has no gap on the home 

### ISSUE THREAD

**Issue by MHamza-Aslam** [piyushgarg-dev/piyushgargdev-nextjs#981]
### Describe the bug

The text of "Full Stack" shows always "Fullstack" which is wrong .

### To Reproduce

1. Go to Home Page
2. Locate Text "Fullstack" in front of Home Page

### Expected behavior

Text of Fullstack always show "Full Stack"

### Screenshots/Videos

![Screenshot 2023-11-01 023133](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/111265281/790e6f26-7777-4229-87fd-978a29d213a8)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by ZEROITRAYO** [comment]
Sir, I have solved the issue. So, please assign me and merge the code.

**Comment by upsaurav12** [comment]
can i work on this issue
